name: 'Dotnet Build and Test'
description:
  'Builds a .NET project, runs tests and handles EF Core migrations including
  rollback on failure'
author: Mario De Benedictis

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  getExecOutput:
    description: 'Verbosity of the workflow'
    required: true
    default: 'true'
  envName:
    description: 'Environment name for ASP.NET Core'
    required: false
    default: 'Test'
  dotnetRoot:
    description: 'Environment name for ASP.NET Core'
    required: false
    default: '/usr/bin/dotnet'

  skipMigrations:
    description: 'Skip applying migrations'
    required: false
    default: 'false'
  migrationsFolder:
    description: 'Path to the migrations folder (default: testFolder)'
    required: false
  useGlobalDotnetEf:
    description: 'Use globally installed dotnet-ef instead of local'
    required: false
    default: 'false'

  skipTests:
    description: 'Skip testing'
    required: false
    default: 'false'
  testFolder:
    description: 'Path to the test project folder'
    required: true
  testFormat:
    description: 'Format for test results (e.g., trx, html, json)'
    required: false
    default: 'html'
  testOutputFolder:
    description: 'Path to the test results output folder'
    required: false
    default: 'TestResults'
  rollbackMigrationsOnTestFailed:
    description: 'Rollback migrations if tests fail'
    required: false

outputs:
  lastMigration:
    description: 'The last applied database migration'
  startTime:
    description: time when workflow started
  endTime:
    description: time when workflow finished

runs:
  using: node20
  main: dist/index.js
